version: '2'

services:

  db:
    image: postgres:9.6
    networks:
      - back-tier
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always


  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/test-rails-app
    networks:
      - back-tier
    entrypoint: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "8088:3000"
    depends_on:
      - db
    restart: always

networks:
  back-tier:
    driver: bridge
